version: '3.8'
services:
  weatherapi:
    image: weather-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080